- backend/controllers/cartsController.js
- backend/models/Cart.js
- backend/routes/cartsRoutes.js
- backend/server.js
- frontend/src/components/Pages/ReservationPage/Reservation.js
- frontend/src/connector.js
createCart is comment out in Reservation.js but it's working.
> Scrum 101 - create cart api

- backend/controllers/classCodeController.js
- backend/models/ClassCode.js
- backend/package-lock.json
- backend/package.json
- backend/routes/classCodeRoutes.js
- backend/server.js
- frontend/src/components/Pages/EnterCode/EnterCode.js
- package-lock.json
1234, class code is in mangoDB
> Scrum 89: create post/get class code api and modify the enterCode.js in front end to adapt the changes

- frontend/package-lock.json
- frontend/package.json
- frontend/public/index.html
- frontend/src/App.js
- frontend/src/components/Functions/PayPal/PayPal.js
- frontend/src/components/Pages/EnterCode/EnterCode.js
- frontend/src/components/Pages/Payment/Payment.css
- frontend/src/components/Pages/Payment/Payment.js
- frontend/src/components/Pages/ReservationPage/Reservation.js
Only frontend is needed for this ticket. 
Go to this branch.
Go inside frontend folder.
npm install.
Go to .env folder in the frontend and add this line:
REACT_APP_PAYPAL_CLIENT_ID=ATa1Ay_BNQzSXAR8JLN0e-UVWnF2fAAwHOXvslTvwxO-dfIaYPWDdJoX6rPZwLun3J5NrvukV0G4UKUa
npm run start.
Go all the way down to Checkout page and click on Checkout button.
You will be navigated to Payment page: http://localhost:3000/Payment
> scrum-87: Paypal Connection 

- frontend/src/components/Dropdown/EquipmentDropdown/EquipmentDropdown.js
- frontend/src/components/Dropdown/PackageDropdown/PackageDropdown.js
- frontend/src/components/Dropdown/PackageEquipmentDropdown/PackageEquipmentDropdown.js
- frontend/src/components/Pages/EnterCode/EnterCode.js
- frontend/src/components/Pages/ReservationPage/Reservation.js
for testing purpose: using 54321 as the class code. 
if you want to create your own test cases:
first add class code: api: http://localhost:3500/api/class-code and body: {
"code": xxxxx
}
and add single/ bundle item to that class code: 
http://localhost:3500/api/bundle-item body: 
{
"bundleId": "B003",
"classCode": "54321",
"bundleName": "Video_Kit",
"items": [
{ "itemName": "Camera_B", "quantity": 1 },
{ "itemName": "Light_B", "quantity": 2 }
],
"price": 450
}
single item: http://localhost:3500/api/single-item
{
"classCode": "54321",
"itemName": "Light_B"
}
> SCRUM-103 update the equipment list for real DB

- backend/controllers/studentsController.js
- backend/models/Student.js
* wait until getting Login info from OIT
> scrum - 98: update student api

- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.js
- frontend/src/components/Pages/ReservationConfirmationMessagePage/ReservationConfirmationMessagePage.css
- frontend/src/components/Pages/ReservationConfirmationMessagePage/ReservationConfirmationMessagePage.js
- package-lock.json
- package.json
The frontend part is done, the bar code generator is now refreshing when you refresh the page but it should be moved to the backend, because when the student refresh the page, they shouldn't get a new code, bar code is generated once the new reservation has been made. Also the back button should route back to the choose class page.
> scrum-86 is done. The reservation confirmation message page frontend

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/Pages/CartConfirmation/CartConfirmation.css
- frontend/src/components/Pages/CartConfirmation/CartConfirmation.js
- frontend/src/components/Pages/ReservationPage/Reservation.css
- frontend/src/components/Pages/ReservationPage/Reservation.js
Most of the cart stuff could be used with the same API as the other one. Not much to be added to it except creating and deleting the cart when going on and off the CartConnfirmartion page and adding routes, updateCart etc.
> Scrum 97 changes

- backend/controllers/cartsController.js
- backend/package-lock.json
- backend/package.json
- backend/routes/cartsRoutes.js
Sorry I did git push while in the frontEnd directory and didnt realise the backend code didnt commit. Its simple as stated before
> Scrum 97 Forgot to Update Backend was in frontEnd Directory

- backend/controllers/orderController.js
- backend/models/Order.js
- backend/routes/orderRoutes.js
- backend/server.js
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/Pages/ReservationConfirmationMessagePage/ReservationConfirmationMessagePage.js
for testing purpose: 
create a order: Post: http://localhost:3500/api/order. body: {
"orderNumber": "Order-123456",
"email": "student@example.com",
"checkin": "2024-09-12T10:00:00Z",
"checkout": "2024-09-18T10:00:00Z",
"studentName": "John Doe"
}
get a order: GET: http://localhost:3500/api/order/Order-123456 
delete a order: DELETE: http://localhost:3500/api/order/Order-123456
get all order: GET: http://localhost:3500/api/orders
> Scrum 113: order API and a template frontend

- frontend/src/App.js
- frontend/src/components/Pages/ViewEquipment/ViewEquipment.js
http://localhost:3000/ViewEquipment
> create ViewEquipment page

- backend/controllers/itemController.js
- backend/models/Item.js
- backend/routes/itemRoutes.js
For Testig purpose: Create or Update Global Item: POST: http://localhost:3500/api/item body:{
"_id": "someMongoDBID",
"itemName": "Camera A",
"pricePerItem": 500,
"itemIds": [
{ "itemId": "CA001", "repair": false, "hide": false },
{ "itemId": "CA002", "repair": false, "hide": false },
{ "itemId": "CA003", "repair": false, "hide": false }
]
}
or:
{
"itemName": "Camera A",
"pricePerItem": 500,
"itemIds": ["CA001", "CA002", "CA003"]
}
change status of repair: PATCH: http://localhost:3500/api/item/E001/repair
Toggle Hide Status by itemId: PATCH: http://localhost:3500/api/item/E001/hide
> scrum-114: Update equipment api

- backend/controllers/classCodeController.js
- backend/models/ClassCode.js
- backend/routes/classCodeRoutes.js
- frontend/src/App.js
- frontend/src/components/Pages/ClassCodesAdmin/ClassCodesAdmin.css
- frontend/src/components/Pages/ClassCodesAdmin/ClassCodesAdmin.js
- frontend/src/components/Pages/ClassCodesEdit/ClassCodesEdit.css
- frontend/src/components/Pages/ClassCodesEdit/ClassCodesEdit.js
- frontend/src/components/Pages/SelectTaskPages/AdminManagementPage/Management.js
- frontend/src/connector.js
Here is the frontend only page for the Class code view. I will connect the backend for the actually data rows later this week
1. Shows all available classes.
2. Can go through multiple pages of classes with the arrows with maximum of 5 rows per page
3. Can type in letters or class name in the search bar to see if a specific class exists
> Scrum-120 - Class Code View Page FE

- frontend/src/components/Button/EditButton/EditButton.css
- frontend/src/components/Functions/AgGridTable/AgGridTable.css
- frontend/src/components/Functions/SearchBar/SearchBar.css
- frontend/src/components/Functions/SearchBar/SearchBar.js
- frontend/src/components/Functions/StudentTable/StudentTable.css
- frontend/src/components/Functions/StudentTable/StudentTable.js
- frontend/src/components/Pages/Students/Students.css
1. Click on the search bar and make placeholder disappear
2. Make search icon stick on the right of the component
3. Make edit button css stays on the same line
4. Make pagination color all blue
5. Make top buttons height taller
6. Make table wider
> Scrum 123 - student page refine css

- backend/models/Item.js
- frontend/package-lock.json
- frontend/src/components/Functions/EquipmentTable/EquipmentTable.js
- frontend/src/components/Functions/SearchBar/SearchBar.js
- frontend/src/components/Pages/Equipment/Equipment.css
- frontend/src/components/Pages/Equipment/Equipment.js
- frontend/src/connector.js
Simply displays data into the equipment page and table. Edit functionality to edit repair and delete items to the backend does not exist yet, will be implemented in scrum-110.
**Changes to the CSS will also be done in another PR of scrum-110**
> scrum-109, display data into equipment page

- backend/controllers/itemController.js
- backend/models/Item.js
- backend/routes/itemRoutes.js
- frontend/src/components/Button/BackButton/BackButton.css
- frontend/src/components/Button/EditButton/EditButton.css
- frontend/src/components/Button/EditButton/EditButton.js
- frontend/src/components/Button/TimeSelectionButton/TimeSelectionButton.css
- frontend/src/components/Button/TimeSelectionButton/TimeSelectionButton.js
- frontend/src/components/Dropdown/EquipmentDropdown/EquipmentDropdown.css
- frontend/src/components/Dropdown/EquipmentDropdown/EquipmentDropdown.js
- frontend/src/components/Dropdown/PackageDropdown/PackageDropdown.css
- frontend/src/components/Dropdown/PackageDropdown/PackageDropdown.js
- frontend/src/components/Functions/AgGridTable/AgGridTable.css
- frontend/src/components/Functions/EquipmentTable/EquipmentTable.css
- frontend/src/components/Functions/EquipmentTable/EquipmentTable.js
- frontend/src/components/Functions/SearchBar/SearchBar.css
- frontend/src/components/Functions/SearchBar/SearchBar.js
- frontend/src/components/Modal/EquipmentPopup/EquipmentPopup.css
- frontend/src/components/Modal/EquipmentPopup/EquipmentPopup.js
- frontend/src/components/Pages/CartConfirmation/CartConfirmation.js
- frontend/src/components/Pages/Equipment/Equipment.js
- frontend/src/components/Pages/ReservationPage/Reservation.js
- frontend/src/components/Pages/SelectTaskPages/AdminViewEquipment/ViewEquipment.js
- frontend/src/components/redux/actions/cartActions.js
- frontend/src/components/redux/actions/reservationCartActions.js
- frontend/src/components/redux/reducers/cartReducers
- frontend/src/components/redux/reducers/index.js
- frontend/src/components/redux/reducers/reservationCartReducers.js
- frontend/src/components/redux/store.js
- frontend/src/connector.js
Will change CSS in the next sprint.
> Scrum 129 - transfer cart items between reservation and cart page

- backend/controllers/itemController.js
- frontend/src/components/Pages/ClassCodesEdit/ClassCodesEdit.js
- frontend/src/connector.js
This fixes the Add modal FUNTIONALITY FOR THE DEMO. The add modal now correctly saves the single items and bundles associated with the class code when a class is added to the backend. It changes up the UI a little, but I will fix this after the Demo so the change in UI doesnt mess anything up functionality wise.
> Demo 120 fix

- backend/controllers/damageReportController.js
- backend/controllers/itemController.js
- backend/models/DamageReport.js
- backend/package-lock.json
- backend/package.json
- backend/routes/damageReportRoutes.js
- backend/routes/itemRoutes.js
- backend/server.js
- frontend/src/App.js
- frontend/src/components/Functions/DamageSearch/DamageSearch.css
- frontend/src/components/Functions/DamageSearch/DamageSearch.js
- frontend/src/components/Functions/DamageTable/DamageTable.css
- frontend/src/components/Functions/DamageTable/DamageTable.js
- frontend/src/components/Modal/DamageReportModal/DamageReportModal.css
- frontend/src/components/Modal/DamageReportModal/DamageReportModal.js
- frontend/src/components/Modal/EquipmentPopup/EquipmentPopup.js
- frontend/src/components/Modal/ViewDamageModal/ViewDamageModal.css
- frontend/src/components/Modal/ViewDamageModal/ViewDamageModal.js
- frontend/src/components/Pages/DamageReport/DamageReport.css
- frontend/src/components/Pages/DamageReport/DamageReport.js
- frontend/src/components/Pages/SelectTaskPages/AdminViewEquipment/ViewEquipment.js
- frontend/src/connector.js
Please ingore the modal reporter is hard coded and the item name didn't have drop down and view report didn't have edit, I will create another PR to handle all of those since each person need 2 PR.
> Scrum 133: Damage report functionnality and most of UI

- frontend/src/components/Functions/TopNavBar/TopNavBar.css
- frontend/src/components/Functions/TopNavBar/TopNavBar.js
- frontend/src/components/Modal/ProfileModal/ProfileModal.css
- frontend/src/components/Modal/ProfileModal/ProfileModal.js
- frontend/src/components/Pages/Login/Login.js
- frontend/src/components/redux/reducers/studentReducer.js
Click the top right icon -> profile, then the profile modal will pop up.
> scrum-145: my profile modal

- frontend/src/components/Pages/CartConfirmation/CartConfirmation.js
- frontend/src/components/Pages/ReservationPage/Reservation.js
bundles.map error occurrs if class code has no equipment or packages. For now, if equipment or packages doesn't exist for a class code, the dropdown will not render for them.
> scrum-163: Conditionally render if equipment/packages have nothing

- frontend/src/components/Functions/DamageTable/DamageTable.js
- frontend/src/components/Modal/DamageReportModal/DamageReportModal.js
- frontend/src/components/Modal/ViewDamageModal/ViewDamageModal.js
> Fix edit functionality - fix-missing-method pushed again

- frontend/src/components/Pages/ReservationConfirmationMessagePage/ReservationConfirmationMessagePage.js
This probably doesn't exist anymore after the pr with forbidding skipping pages with url, but just to be safe, I clear the cart in redux store after message confirmation
> scrum-181: Clear cart after order confirmation

- backend/controllers/studentsController.js
- backend/models/Student.js
- frontend/src/components/Dropdown/RoleDropdown/RoleDropdown.css
- frontend/src/components/Dropdown/RoleDropdown/RoleDropdown.js
- frontend/src/components/Functions/ReservationTable/ReservationTable.js
- frontend/src/components/Modal/ScanPopup/ScanPopup.css
- frontend/src/components/Modal/ScanPopup/ScanPopup.js
- frontend/src/components/Modal/SearchPopup/SearchPopup.css
- frontend/src/components/Modal/SearchPopup/SearchPopupCheckin.js
- frontend/src/components/Pages/CartConfirmation/CartConfirmation.js
- frontend/src/components/Pages/Login/Login.js
- frontend/src/components/Pages/Payment/Payment.js
- frontend/src/components/Pages/ReservationPage/Reservation.js
- frontend/src/components/Pages/SelectTaskPages/AdminSelectTaskPage/SelectTask.js
- frontend/src/components/Pages/SelectTaskPages/AdminViewEquipment/ViewEquipment.js
Scrum-177: https://qihui1002.atlassian.net/jira/software/projects/SCRUM/boards/1?assignee=712020%3A7b04f5e4-5741-48aa-8369-3407eba9e295&selectedIssue=SCRUM-177
Scrum-180: https://qihui1002.atlassian.net/jira/software/projects/SCRUM/boards/1?assignee=712020%3A7b04f5e4-5741-48aa-8369-3407eba9e295&selectedIssue=SCRUM-180
We have some UI questions (part 2 of scrum-177) for the client so "Professor can make reservation for free" is not implemented yet.
Summary of my changes:
1. If checkedin itemID does not match with existing checkedout itemID, show error of “Your Checkin itemID does not match with Checkout itemID“.
2. ⁠Reverse order so that newly created is displayed on top of table
⁠3. processor can only access Reserve Equipment and View Equipment (only Equipment)
4. Refined error message …
> Scrum 177 and scrum - 180

- backend/controllers/itemController.js
- frontend/src/components/Functions/CodesTable/CodesTable.js
- frontend/src/components/Functions/DamageTable/DamageTable.js
- frontend/src/components/Functions/StudentTable/StudentTable.js
Delete popup added to the following pages:
- Class Codes Page
- Students Page
- Damage Report Page
> scrum-173: Add popup alert to table pages

- frontend/src/components/Modal/ReservationDetailPopup/ReservationDetailPopup.js
- frontend/src/components/Modal/ViewExtendOrder/ViewExtendOrder.css
- frontend/src/components/Modal/ViewExtendOrder/ViewExtendOrder.js
Cant extend an order when the checkout date has passed
> Scrum 190 - Cant extend order if checkout date passed Bug

- frontend/src/components/Modal/SearchPopup/SearchPopup.js
Version 1: 
Version 2 with another <p>:
Version 3 with no <p>:
> scrum-188 update

- README.md
- backend/controllers/studentsController.js
- backend/models/Student.js
- frontend/src/components/Dropdown/RoleDropdown/RoleDropdown.js
- frontend/src/components/Functions/TopNavBar/TopNavBar.js
- frontend/src/components/Modal/ReservationDetailPopup/ReservationDetailPopup.js
- frontend/src/components/Modal/SearchPopup/SearchPopup.js
- frontend/src/components/Modal/SearchPopup/SearchPopupCheckin.js
- frontend/src/components/Pages/Login/Login.js
- frontend/src/components/Pages/SelectTaskPages/AdminSelectTaskPage/SelectTask.js
> Scrum - 206: Adjust View Reservation Equipment Checkout Modal Error Message Styling

- backend/controllers/damageReportController.js
- backend/models/DamageReport.js
- frontend/src/components/Modal/DamageReportModal/DamageReportModal.js
- frontend/src/components/Modal/ViewDamageModal/ViewDamageModal.css
- frontend/src/components/Modal/ViewDamageModal/ViewDamageModal.js
> Scrum 200: update damage report modal to add a order number attribute

- backend/controllers/itemController.js
- backend/controllers/orderController.js
- backend/routes/itemRoutes.js
- frontend/src/components/Button/TimeSelectionButton/TimeSelectionButton.js
- frontend/src/components/Dropdown/PackageEquipmentDropdown/PackageEquipmentDropdown.js
- frontend/src/components/Functions/PayPal/PayPal.js
- frontend/src/components/Functions/ReservationHistoryTable/ReservationHistoryTable.js
- frontend/src/components/Modal/BarCodePopup/BarCodePopup.js
- frontend/src/components/Modal/ReservationDetailPopup/ReservationDetailPopup.css
- frontend/src/components/Modal/ReservationDetailPopup/ReservationDetailPopup.js
- frontend/src/components/Modal/StudentViewDamageModal/StudentViewDamageModal.css
- frontend/src/components/Modal/StudentViewDamageModal/StudentViewDamageModal.js
- frontend/src/components/Pages/Payment/Payment.js
- frontend/src/components/Pages/ReservationConfirmationMessagePage/ReservationConfirmationMessagePage.js
- frontend/src/components/Pages/ReservationPage/Reservation.css
- frontend/src/components/Pages/ReservationPage/Reservation.js
- frontend/src/components/Pages/ReservationTimePicker/ReservationTimePicker.js
- frontend/src/connector.js
Fixes previous merge problem to only make one order instead of two.
Addresses multiple tickets at the same time:
scrum-182
198
196
171
in progress:
167
> [DONT MERGE] scrum-182: Fix to make only one order

- backend/controllers/itemController.js
- backend/controllers/orderController.js
- backend/routes/itemRoutes.js
- frontend/src/components/Button/TimeSelectionButton/TimeSelectionButton.js
- frontend/src/components/Dropdown/PackageEquipmentDropdown/PackageEquipmentDropdown.js
- frontend/src/components/Functions/PayPal/PayPal.js
- frontend/src/components/Functions/ReservationHistoryTable/ReservationHistoryTable.js
- frontend/src/components/Modal/BarCodePopup/BarCodePopup.js
- frontend/src/components/Modal/ReservationDetailPopup/ReservationDetailPopup.css
- frontend/src/components/Modal/ReservationDetailPopup/ReservationDetailPopup.js
- frontend/src/components/Modal/StudentViewDamageModal/StudentViewDamageModal.css
- frontend/src/components/Modal/StudentViewDamageModal/StudentViewDamageModal.js
- frontend/src/components/Modal/ViewExtendOrder/ViewExtendOrder.css
- frontend/src/components/Pages/Payment/Payment.js
- frontend/src/components/Pages/ReservationConfirmationMessagePage/ReservationConfirmationMessagePage.js
- frontend/src/components/Pages/ReservationPage/Reservation.css
- frontend/src/components/Pages/ReservationPage/Reservation.js
- frontend/src/components/Pages/ReservationTimePicker/ReservationTimePicker.js
- frontend/src/connector.js
First error: Somehow the admin would be sent two emails instead of one when confirming order with new code, made it so only one would be sent now through a checking system
Second Error. Reserbation history table didnt properly update when cancel order and extend order were selected. Fixed
Third change (not error): More quality of life update- Disabled done button in extend order until both date and time are selected
> Scrum 182 errors found and fixed

- frontend/src/components/Modal/SearchPopup/SearchPopup.js
> Scrum 199 - ItemID shouldn't be repetitive (Dont merge since its still built off the 182-error branch)

- backend/controllers/emailController.js
- frontend/src/components/Functions/ReservationHistoryTable/ReservationHistoryTable.js
- frontend/src/components/Modal/DamageReportModal/DamageReportModal.css
- frontend/src/components/Modal/DamageReportModal/DamageReportModal.js
- frontend/src/components/Pages/ReservationPage/Reservation.js
Can now add up to the quantity of the item in cart
Fixed some minor errors didnt see when merging from main:
-Reservation history table order needed to be reversed
-view bar code and view detail popup code somehow got altered on the reservation history table, tiny quick fixes to make it completely work again
> Fixed Can only reserve up to Quantitiy in Cart and other minor errors from merge

- frontend/src/components/Functions/DamageTable/DamageTable.css
- frontend/src/components/Functions/DamageTable/DamageTable.js
- frontend/src/components/Functions/EquipmentTable/EquipmentTable.css
- frontend/src/components/Functions/EquipmentTable/EquipmentTable.js
- frontend/src/components/Functions/TopNavBar/TopNavBar.js
- frontend/src/components/Modal/Terms/TermsModal.css
- frontend/src/components/Modal/Terms/TermsModal.js
- frontend/src/components/Pages/CartConfirmation/CartConfirmation.css
- frontend/src/components/Pages/CartConfirmation/CartConfirmation.js
- frontend/src/components/Pages/ReservationTimePicker/ReservationTimePicker.css
Scrum 166: 
Titles on those pages containing tables are consistent; the rest are also consistent. 
Scrum 203:
For repair column in equipment page, change title to "Repair Status" and the dropdown options to be "Out for repair", "Currently Available" or something like that instead of yes or no
Nav Bar Bug:
When click "X" button, it will close and reopen. Now the issue is fixed.
> Scrum 166 + Scrum 203

- installation.md
The file contains all of the following below. My idea is that the file is hosted in this repository, and in the README.md file, we just permalink it to this file.
The following contains the process and requirements to install and run this project.
- Git >= `2.41.x`
- Node >= `v18.x.x`
- Mongo backend URI
- Paypal client ID
```
git clone https://github.com/Qihuiwang3/JID-4121-LMCFilm.git
```
```
cd frontend
npm i
cd backend
npm i
```
```
REACT_APP_BACKEND_URL=http://localhost:3500
REACT_APP_PAYPAL_CLIENT_ID=[paypal client id]
JWT_SECRET=[random jwt secret]
```
```
NODE_ENV=development 
DATABASE_URI=[mongo backend URI]
```
```
cd frontend
npm run start
cd backend
npm run dev
```
> installation guide
